#!/usr/bin/env ruby
# Usage: script/parse /path/to/captured_data.out
#        cat captured_data.out | script/parse

require "csv"

# load prefixes table
prefixes = {}
CSV.foreach(File.expand_path("../../binary_tables/prefixes.csv", __FILE__)) do |row|
  next if row == ["type", "prefix"]
  prefixes[row[1]] = row[0]
end

ARGF.each do |line|
  # get rid of anything that isn't a 0 or 1
  line.gsub!(/[^0-1]/, '')

  prefixes.each do |key, value|
    next unless line[0..key.length-1] == key

    line = value
  end

  puts line
end
